version: '3'


services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    # volumes:
    #   - ./client:/client
    command: python ./client.py
    depends_on:
      - server
    networks:
      - my-network
    
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./data:/lab1/data
    command: python ./server.py
    ports:
      - "5000:5000"
    networks:
      - my-network
networks:
  my-network: