version: '3'


services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    #command: python ./client.py
    # network_mode: host
    depends_on:
      - server
  
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
    - ./data:/data
    #command: python ./server.py
    # network_mode: host
    # command: ["python", "server.py", "flask", "run", "--host=0.0.0.0"]
    ports:
      - 5000:5000
